sudo: false

language: go

go:
 - 1.8

before_install:
 - go get github.com/stretchr/testify/assert
 - go get github.com/mattn/goveralls

script:
 - go get -d -t -v ./...
 - go build -x -v ./...
 - go test -a -x -v ./...
 - go test -a -tags bounds -x -v ./...
 - go test -a -tags noasm -x -v ./...
 - go test -a -tags appengine -x -v ./...
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .travis/test-coverage.sh; fi